src/Entity/Notification.php
<?php

namespace App\Entity;

use App\Repository\NotificationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: NotificationRepository::class)]
class Notification
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $message = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $sent_date = null;

    /**
     * @var Collection<int, Evenement>
     */
    #[ORM\OneToMany(targetEntity: Evenement::class, mappedBy: 'notification', orphanRemoval: true)]
    private Collection $evenement_id;

    public function __construct()
    {
        $this->evenement_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getSentDate(): ?\DateTimeInterface
    {
        return $this->sent_date;
    }

    public function setSentDate(\DateTimeInterface $sent_date): static
    {
        $this->sent_date = $sent_date;

        return $this;
    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvenementId(): Collection
    {
        return $this->evenement_id;
    }

    public function addEvenementId(Evenement $evenementId): static
    {
        if (!$this->evenement_id->contains($evenementId)) {
            $this->evenement_id->add($evenementId);
            $evenementId->setNotification($this);
        }

        return $this;
    }

    public function removeEvenementId(Evenement $evenementId): static
    {
        if ($this->evenement_id->removeElement($evenementId)) {
            // set the owning side to null (unless already changed)
            if ($evenementId->getNotification() === $this) {
                $evenementId->setNotification(null);
            }
        }

        return $this;
    }
}

src/Form/NotificationType.php
<?php

namespace App\Form;

use App\Entity\Notification;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NotificationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('message')
            ->add('sent_date', null, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Notification::class,
        ]);
    }
}

src/Controller/NotificationController.php
<?php

namespace App\Controller;

use App\Entity\Notification;
use App\Form\NotificationType;
use App\Repository\NotificationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/notification')]
final class NotificationController extends AbstractController
{
    #[Route(name: 'app_notification_index', methods: ['GET'])]
    public function index(NotificationRepository $notificationRepository): Response
    {
        return $this->render('notification/index.html.twig', [
            'notifications' => $notificationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_notification_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $notification = new Notification();
        $form = $this->createForm(NotificationType::class, $notification);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($notification);
            $entityManager->flush();

            return $this->redirectToRoute('app_notification_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('notification/new.html.twig', [
            'notification' => $notification,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_notification_show', methods: ['GET'])]
    public function show(Notification $notification): Response
    {
        return $this->render('notification/show.html.twig', [
            'notification' => $notification,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_notification_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Notification $notification, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(NotificationType::class, $notification);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_notification_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('notification/edit.html.twig', [
            'notification' => $notification,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_notification_delete', methods: ['POST'])]
    public function delete(Request $request, Notification $notification, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$notification->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($notification);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_notification_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/notification/_delete_form.html.twig
<form method="post" action="{{ path('app_notification_delete', {'id': notification.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ notification.id) }}">
    <button class="btn">Delete</button>
</form>

templates/notification/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/notification/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Notification{% endblock %}

{% block body %}
    <h1>Edit Notification</h1>

    {{ include('notification/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_notification_index') }}">back to list</a>

    {{ include('notification/_delete_form.html.twig') }}
{% endblock %}

templates/notification/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notification index{% endblock %}

{% block body %}
    <h1>Notification index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Message</th>
                <th>Sent_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for notification in notifications %}
            <tr>
                <td>{{ notification.id }}</td>
                <td>{{ notification.message }}</td>
                <td>{{ notification.sentDate ? notification.sentDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_notification_show', {'id': notification.id}) }}">show</a>
                    <a href="{{ path('app_notification_edit', {'id': notification.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_notification_new') }}">Create new</a>
{% endblock %}

templates/notification/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Notification{% endblock %}

{% block body %}
    <h1>Create new Notification</h1>

    {{ include('notification/_form.html.twig') }}

    <a href="{{ path('app_notification_index') }}">back to list</a>
{% endblock %}

templates/notification/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notification{% endblock %}

{% block body %}
    <h1>Notification</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ notification.id }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ notification.message }}</td>
            </tr>
            <tr>
                <th>Sent_date</th>
                <td>{{ notification.sentDate ? notification.sentDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_notification_index') }}">back to list</a>

    <a href="{{ path('app_notification_edit', {'id': notification.id}) }}">edit</a>

    {{ include('notification/_delete_form.html.twig') }}
{% endblock %}