src/Entity/Paiement.php
<?php

namespace App\Entity;

use App\Repository\PaiementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaiementRepository::class)]
class Paiement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $montant = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column(length: 255)]
    private ?string $mode_paiement = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $payment_date = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?inscription $inscription_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getModePaiement(): ?string
    {
        return $this->mode_paiement;
    }

    public function setModePaiement(string $mode_paiement): static
    {
        $this->mode_paiement = $mode_paiement;

        return $this;
    }

    public function getPaymentDate(): ?\DateTimeInterface
    {
        return $this->payment_date;
    }

    public function setPaymentDate(\DateTimeInterface $payment_date): static
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    public function getInscriptionId(): ?inscription
    {
        return $this->inscription_id;
    }

    public function setInscriptionId(inscription $inscription_id): static
    {
        $this->inscription_id = $inscription_id;

        return $this;
    }
}

src/Form/PaiementType.php
<?php

namespace App\Form;

use App\Entity\inscription;
use App\Entity\Paiement;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaiementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('montant')
            ->add('reference')
            ->add('mode_paiement')
            ->add('payment_date', null, [
                'widget' => 'single_text',
            ])
            ->add('inscription_id', EntityType::class, [
                'class' => inscription::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Paiement::class,
        ]);
    }
}

src/Controller/PaiementController.php
<?php

namespace App\Controller;

use App\Entity\Paiement;
use App\Form\PaiementType;
use App\Repository\PaiementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/paiement')]
final class PaiementController extends AbstractController
{
    #[Route(name: 'app_paiement_index', methods: ['GET'])]
    public function index(PaiementRepository $paiementRepository): Response
    {
        return $this->render('paiement/index.html.twig', [
            'paiements' => $paiementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_paiement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $paiement = new Paiement();
        $form = $this->createForm(PaiementType::class, $paiement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($paiement);
            $entityManager->flush();

            return $this->redirectToRoute('app_paiement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('paiement/new.html.twig', [
            'paiement' => $paiement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_paiement_show', methods: ['GET'])]
    public function show(Paiement $paiement): Response
    {
        return $this->render('paiement/show.html.twig', [
            'paiement' => $paiement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_paiement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Paiement $paiement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PaiementType::class, $paiement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_paiement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('paiement/edit.html.twig', [
            'paiement' => $paiement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_paiement_delete', methods: ['POST'])]
    public function delete(Request $request, Paiement $paiement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$paiement->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($paiement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_paiement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/paiement/_delete_form.html.twig
<form method="post" action="{{ path('app_paiement_delete', {'id': paiement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paiement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/paiement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/paiement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Paiement{% endblock %}

{% block body %}
    <h1>Edit Paiement</h1>

    {{ include('paiement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_paiement_index') }}">back to list</a>

    {{ include('paiement/_delete_form.html.twig') }}
{% endblock %}

templates/paiement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement index{% endblock %}

{% block body %}
    <h1>Paiement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Montant</th>
                <th>Reference</th>
                <th>Mode_paiement</th>
                <th>Payment_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for paiement in paiements %}
            <tr>
                <td>{{ paiement.id }}</td>
                <td>{{ paiement.montant }}</td>
                <td>{{ paiement.reference }}</td>
                <td>{{ paiement.modePaiement }}</td>
                <td>{{ paiement.paymentDate ? paiement.paymentDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_paiement_show', {'id': paiement.id}) }}">show</a>
                    <a href="{{ path('app_paiement_edit', {'id': paiement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_paiement_new') }}">Create new</a>
{% endblock %}

templates/paiement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Paiement{% endblock %}

{% block body %}
    <h1>Create new Paiement</h1>

    {{ include('paiement/_form.html.twig') }}

    <a href="{{ path('app_paiement_index') }}">back to list</a>
{% endblock %}

templates/paiement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement{% endblock %}

{% block body %}
    <h1>Paiement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ paiement.id }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ paiement.montant }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ paiement.reference }}</td>
            </tr>
            <tr>
                <th>Mode_paiement</th>
                <td>{{ paiement.modePaiement }}</td>
            </tr>
            <tr>
                <th>Payment_date</th>
                <td>{{ paiement.paymentDate ? paiement.paymentDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_paiement_index') }}">back to list</a>

    <a href="{{ path('app_paiement_edit', {'id': paiement.id}) }}">edit</a>

    {{ include('paiement/_delete_form.html.twig') }}
{% endblock %}