src/Entity/Inscription.php
<?php

namespace App\Entity;

use App\Repository\InscriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InscriptionRepository::class)]
class Inscription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $registration_date = null;

    /**
     * @var Collection<int, participant>
     */
    #[ORM\OneToMany(targetEntity: participant::class, mappedBy: 'inscription', orphanRemoval: true)]
    private Collection $participant_id;

    /**
     * @var Collection<int, Evenement>
     */
    #[ORM\OneToMany(targetEntity: Evenement::class, mappedBy: 'inscription', orphanRemoval: true)]
    private Collection $evenement_id;

    public function __construct()
    {
        $this->participant_id = new ArrayCollection();
        $this->evenement_id = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(\DateTimeInterface $registration_date): static
    {
        $this->registration_date = $registration_date;

        return $this;
    }

    /**
     * @return Collection<int, participant>
     */
    public function getParticipantId(): Collection
    {
        return $this->participant_id;
    }

    public function addParticipantId(participant $participantId): static
    {
        if (!$this->participant_id->contains($participantId)) {
            $this->participant_id->add($participantId);
            $participantId->setInscription($this);
        }

        return $this;
    }

    public function removeParticipantId(participant $participantId): static
    {
        if ($this->participant_id->removeElement($participantId)) {
            // set the owning side to null (unless already changed)
            if ($participantId->getInscription() === $this) {
                $participantId->setInscription(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Evenement>
     */
    public function getEvenementId(): Collection
    {
        return $this->evenement_id;
    }

    public function addEvenementId(Evenement $evenementId): static
    {
        if (!$this->evenement_id->contains($evenementId)) {
            $this->evenement_id->add($evenementId);
            $evenementId->setInscription($this);
        }

        return $this;
    }

    public function removeEvenementId(Evenement $evenementId): static
    {
        if ($this->evenement_id->removeElement($evenementId)) {
            // set the owning side to null (unless already changed)
            if ($evenementId->getInscription() === $this) {
                $evenementId->setInscription(null);
            }
        }

        return $this;
    }
}

src/Form/InscriptionType.php
<?php

namespace App\Form;

use App\Entity\Inscription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('registration_date', null, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inscription::class,
        ]);
    }
}

src/Controller/InscriptionController.php
<?php

namespace App\Controller;

use App\Entity\Inscription;
use App\Form\InscriptionType;
use App\Repository\InscriptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/inscription')]
final class InscriptionController extends AbstractController
{
    #[Route(name: 'app_inscription_index', methods: ['GET'])]
    public function index(InscriptionRepository $inscriptionRepository): Response
    {
        return $this->render('inscription/index.html.twig', [
            'inscriptions' => $inscriptionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_inscription_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $inscription = new Inscription();
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($inscription);
            $entityManager->flush();

            return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inscription/new.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_inscription_show', methods: ['GET'])]
    public function show(Inscription $inscription): Response
    {
        return $this->render('inscription/show.html.twig', [
            'inscription' => $inscription,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_inscription_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Inscription $inscription, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InscriptionType::class, $inscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inscription/edit.html.twig', [
            'inscription' => $inscription,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_inscription_delete', methods: ['POST'])]
    public function delete(Request $request, Inscription $inscription, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inscription->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($inscription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_inscription_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inscription/_delete_form.html.twig
<form method="post" action="{{ path('app_inscription_delete', {'id': inscription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inscription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/inscription/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/inscription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Inscription{% endblock %}

{% block body %}
    <h1>Edit Inscription</h1>

    {{ include('inscription/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_inscription_index') }}">back to list</a>

    {{ include('inscription/_delete_form.html.twig') }}
{% endblock %}

templates/inscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription index{% endblock %}

{% block body %}
    <h1>Inscription index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Registration_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for inscription in inscriptions %}
            <tr>
                <td>{{ inscription.id }}</td>
                <td>{{ inscription.registrationDate ? inscription.registrationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_inscription_show', {'id': inscription.id}) }}">show</a>
                    <a href="{{ path('app_inscription_edit', {'id': inscription.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_inscription_new') }}">Create new</a>
{% endblock %}

templates/inscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Inscription{% endblock %}

{% block body %}
    <h1>Create new Inscription</h1>

    {{ include('inscription/_form.html.twig') }}

    <a href="{{ path('app_inscription_index') }}">back to list</a>
{% endblock %}

templates/inscription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription{% endblock %}

{% block body %}
    <h1>Inscription</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ inscription.id }}</td>
            </tr>
            <tr>
                <th>Registration_date</th>
                <td>{{ inscription.registrationDate ? inscription.registrationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_inscription_index') }}">back to list</a>

    <a href="{{ path('app_inscription_edit', {'id': inscription.id}) }}">edit</a>

    {{ include('inscription/_delete_form.html.twig') }}
{% endblock %}